apiVersion: v1
kind: Namespace
metadata:
  name: csi-qingcloud

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: csi-qingcloud
  namespace: csi-qingcloud
data:
  config.yaml: |
    qy_access_key_id: 'ACCESS_KEY_ID'
    qy_secret_access_key: 'SECRET_ACCESS_KEY'
    zone: 'ZONE'
    host: 'api.qingcloud.com'
    port: 443
    protocol: 'https'
    uri: '/iaas'
    connection_retries: 3
    connection_timeout: 30
