## In production, this needs to be in separate files, e.g. service account and
# role and role binding needs to be created once, while stateful set may
# require some tuning.

# For StatefulSet validation
kind: Service
apiVersion: v1
metadata:
  name: csi-qingcloud-controller
  namespace: csi-qingcloud
  labels:
    app: csi-qingcloud
    tier: controller
spec:
  selector:
    app: csi-qingcloud
    tier: controller
  ports:
    - name: dummy
      port: 12345
---

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-qingcloud-controller
  namespace: csi-qingcloud
spec:
  serviceName: "csi-qingcloud-controller"
  selector:
    matchLabels:
      app: csi-qingcloud
      tier: controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-qingcloud
        tier: controller
    spec:
      serviceAccount: csi-qingcloud-controller
# The private registry secret must exist before creating this workload.
# Create csi-registry secret command:
#   kubectl create secret docker-registry csi-registry --docker-server=dockerhub.qingcloud.com \\
#     --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
      imagePullSecrets:
      - name: csi-registry
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v0.2.1
          args:
            - "--provisioner=csi-qingcloud"
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
        - name: csi-qingcloud
          image: dockerhub.qingcloud.com/wiley/csi-qingcloud:v0.2.0.1
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--v=5"
            - "--drivername=csi-qingcloud"
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy
            - name: server-config
              mountPath: /root
      volumes:
        - name: socket-dir
          emptyDir:
        - name: server-config
          configMap:
            name: csi-qingcloud
