apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-qingcloud-node
  namespace: csi-qingcloud

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-qingcloud-node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-qingcloud-node
subjects:
  - kind: ServiceAccount
    name: csi-qingcloud-node
    namespace: csi-qingcloud
roleRef:
  kind: ClusterRole
  name: csi-qingcloud-node
  apiGroup: rbac.authorization.k8s.io
